import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/navbar/Navbar'
import Container from '@/components/global/Container'
import { Exo_2 } from 'next/font/google'
import { AuthProvider } from '@/context/AuthContext'
import { AlertProvider } from '@/context/AlertContext'
import GlobalAlert from '@/components/global/GlobalAlert'

const exo2 = Exo_2({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  style: ['normal', 'italic'],
  display: 'swap', // Better performance
})

export const metadata = {
  title: 'Flutter Social',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${exo2.className} antialiased relative`}>
        <AlertProvider>
          <AuthProvider>
            <GlobalAlert />
            <Navbar />
            <Container className='h-screen max-w-[1400px] mx-auto'>
              {children}
            </Container>
          </AuthProvider>
        </AlertProvider>
      </body>
    </html>
  )
}
